name: Update README with PRs and Issues

on:
  issues:
    types: [opened, edited, closed]
  pull_request:
    types: [opened, edited, closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt-get update
          sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: |
          echo ${{ secrets.GH_TOKEN }} | gh auth login --with-token

      - name: Get PRs and Issues
        run: |
          echo "## Pull Requests" > pr_issue_list.md
          gh pr list --limit 5 --json number,title,url --template '{{range .}}- [#{{.number}}]({{.url}}): {{.title}}\n{{end}}' >> pr_issue_list.md
          echo "\n## Issues" >> pr_issue_list.md
          gh issue list --limit 5 --json number,title,url --template '{{range .}}- [#{{.number}}]({{.url}}): {{.title}}\n{{end}}' >> pr_issue_list.md

      - name: Update README
        run: |
          cat pr_issue_list.md >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update README with latest PRs and Issues"
          git push
