name: Update README with PRs and Issues

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, edited, closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

      - name: Get the new issue
        id: issue
        run: |
          echo "::set-output name=number::$(gh issue view ${{ github.event.issue.number }} --json number --jq .number)"
          echo "::set-output name=title::$(gh issue view ${{ github.event.issue.number }} --json title --jq .title)"
          echo "::set-output name=url::$(gh issue view ${{ github.event.issue.number }} --json url --jq .url)"
          
      - name: Update README with new issue
        run: |
          echo "- [#${{ steps.issue.outputs.number }}](${{ steps.issue.outputs.url }}): ${{ steps.issue.outputs.title }}" >> README.md

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'KimGSeok'
          git config --global user.email 'rla99tjr@gmail.com'
          git add README.md
          git commit -m "Update README with new issue #${{ steps.issue.outputs.number }}"
          git push origin main
